function [  ] = plotpath( path, grid )
%This function plots the path generated by AstarSearch function or the smooth path
%generated by the smooth function against the grid. The size of the grid is
%used to define the boundaries.
%
% Example use:
% figure,
% plotpath(newpath,grid)
%
plot(path(:,2),path(:,1))
set(gca,'xlim',[0 size(grid,2)+1])
set(gca,'ylim',[0 size(grid,1)+1])
hold on
for m = 1:size(grid,1)
    for n = 1:size(grid,2)
        if(grid(m,n) == 1)
            scatter(n,m)
        end
    end
end
end

